### PR TITLE
New Phoenix Logo

### PR DESCRIPTION
**Pull request by elseloop**
We have a new logo! 

* adds the new logo
* updates our color scheme to match new branding
* updates the Sassdoc theme to match new branding

### CODE REVIEW

**Comment by kamsar** [comment]
Love it :+1:

**Comment by ajmueller** [comment]
Seconded :+1:

**Comment by kamsar** [comment]
Patrick's work. Look familiar? http://kamsar.net/index.php/2015/09/Unicorn-3-What-s-new/Unicorn_logo.png

**Comment by ajmueller** [comment]
Yep!  But I want to know where the Unicorn love is on https://www.connectivedx.com/tools

**Comment by ajmueller** [comment]
Also, I'm not sure if it's on your guys' radar, but the background on the blog post is the old logo.  It looks like the Tools page was updated, though.

https://www.connectivedx.com/thinking/posts/2015/01/phoenix-front-end-development-framework

**Pull request merged**
