### PR TITLE
Release 2.2.0

### PR DESCRIPTION
**Pull request by elseloop**

### CODE REVIEW

**Comment by ajmueller** [comment]
Please check my note on #178.  It might be worth waiting for the next minor version of clean-css to get media query combining to work properly.

**Comment by elseloop** [comment]
Thanks, @ajmueller. I agree, of course, but I think moving ahead with this change is worthwhile anyway. Hear me out:

We pull `gulp-combine-media-queries` now, let `clean-css` handle it when that enhancement is released (bumping the required version on that accordingly then), and live with the slightly larger file size in the interim. I've landed there primarily because leaving `gulp-combine-media-queries` in as it stands breaks the production build and any alternatives I've been able to find—band aids that might hold us over before the next minor release of `clean-css`—appear to be just as unmaintained/unhelpful as `gulp-combine-media-queries`. This at least gets us to a clean production build on `master` today. 

I'm going to hold off on merging this in, as I'd like your input (and may circulate it around a bit). Thanks again for throwing up your hands on this.

**Comment by ajmueller** [comment]
Oh I totally agree; in fact it's what I did with the client where I discovered the issue (removed `gulp-combine-media-queries` for now and will update `gulp-minify-css` later), I just wanted to make sure you were fully aware of the issue.  Go forth and ignore me!

**Comment by elseloop** [comment]
Cool. Cool cool cool. GOING FOR IT!

**Comment by ajmueller** [comment]
I find the lack of an Abed GIF in your previous comment disturbing...I must remedy that.

Cool cool cool

**Pull request merged**
